version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    links:
      - chat
    volumes:
      - .:/home/app
  chat:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=agus
      - MONGO_INITDB_ROOT_PASSWORD=burgger12
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data